version: "2"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: should have comment
      - path: (.+)\.go$
        text: should have a package comment
      - path: (.+)\.go$
        text: error strings should not be capitalized or end with punctuation or a newline
      - path: (.+)\.go$
        text: don't use ALL_CAPS in Go names
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
