// Code generated by "stringer -type=OfflineReason -output=heal-commands-offline-reason_gen.go -trimprefix=OfflineReason heal-commands.go"; DO NOT EDIT.

package madmin

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OfflineReasonInvalid-0]
	_ = x[OfflineReasonNodeDown-1]
	_ = x[OfflineReasonDriveIOError-2]
	_ = x[OfflineReasonDriveDown-3]
	_ = x[OfflineReasonDriveTimeout-4]
}

const _OfflineReason_name = "InvalidNodeDownDriveIOErrorDriveDownDriveTimeout"

var _OfflineReason_index = [...]uint8{0, 7, 15, 27, 36, 48}

func (i OfflineReason) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OfflineReason_index)-1 {
		return "OfflineReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OfflineReason_name[_OfflineReason_index[idx]:_OfflineReason_index[idx+1]]
}
