// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package madmin

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *GaugeStats) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 4 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "n":
			z.N, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "N")
				return
			}
			zb0001Mask |= 0x1
		case "sum":
			z.Sum, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Sum")
				return
			}
			zb0001Mask |= 0x2
		case "min":
			z.Min, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Min")
				return
			}
			zb0001Mask |= 0x4
		case "max":
			z.Max, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Max")
				return
			}
			zb0001Mask |= 0x8
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0xf {
		if (zb0001Mask & 0x1) == 0 {
			z.N = 0
		}
		if (zb0001Mask & 0x2) == 0 {
			z.Sum = 0
		}
		if (zb0001Mask & 0x4) == 0 {
			z.Min = 0
		}
		if (zb0001Mask & 0x8) == 0 {
			z.Max = 0
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *GaugeStats) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(4)
	var zb0001Mask uint8 /* 4 bits */
	_ = zb0001Mask
	if z.N == 0 {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.Sum == 0 {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Min == 0 {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Max == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// write "n"
			err = en.Append(0xa1, 0x6e)
			if err != nil {
				return
			}
			err = en.WriteInt(z.N)
			if err != nil {
				err = msgp.WrapError(err, "N")
				return
			}
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "sum"
			err = en.Append(0xa3, 0x73, 0x75, 0x6d)
			if err != nil {
				return
			}
			err = en.WriteFloat64(z.Sum)
			if err != nil {
				err = msgp.WrapError(err, "Sum")
				return
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "min"
			err = en.Append(0xa3, 0x6d, 0x69, 0x6e)
			if err != nil {
				return
			}
			err = en.WriteFloat64(z.Min)
			if err != nil {
				err = msgp.WrapError(err, "Min")
				return
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "max"
			err = en.Append(0xa3, 0x6d, 0x61, 0x78)
			if err != nil {
				return
			}
			err = en.WriteFloat64(z.Max)
			if err != nil {
				err = msgp.WrapError(err, "Max")
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *GaugeStats) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(4)
	var zb0001Mask uint8 /* 4 bits */
	_ = zb0001Mask
	if z.N == 0 {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.Sum == 0 {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Min == 0 {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Max == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// string "n"
			o = append(o, 0xa1, 0x6e)
			o = msgp.AppendInt(o, z.N)
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "sum"
			o = append(o, 0xa3, 0x73, 0x75, 0x6d)
			o = msgp.AppendFloat64(o, z.Sum)
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "min"
			o = append(o, 0xa3, 0x6d, 0x69, 0x6e)
			o = msgp.AppendFloat64(o, z.Min)
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "max"
			o = append(o, 0xa3, 0x6d, 0x61, 0x78)
			o = msgp.AppendFloat64(o, z.Max)
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *GaugeStats) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 4 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "n":
			z.N, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "N")
				return
			}
			zb0001Mask |= 0x1
		case "sum":
			z.Sum, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Sum")
				return
			}
			zb0001Mask |= 0x2
		case "min":
			z.Min, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Min")
				return
			}
			zb0001Mask |= 0x4
		case "max":
			z.Max, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Max")
				return
			}
			zb0001Mask |= 0x8
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0xf {
		if (zb0001Mask & 0x1) == 0 {
			z.N = 0
		}
		if (zb0001Mask & 0x2) == 0 {
			z.Sum = 0
		}
		if (zb0001Mask & 0x4) == 0 {
			z.Min = 0
		}
		if (zb0001Mask & 0x8) == 0 {
			z.Max = 0
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *GaugeStats) Msgsize() (s int) {
	s = 1 + 2 + msgp.IntSize + 4 + msgp.Float64Size + 4 + msgp.Float64Size + 4 + msgp.Float64Size
	return
}
