// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package madmin

import (
	"time"

	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *ILMMetrics) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 5 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "collected":
			z.CollectedAt, err = dc.ReadTimeUTC()
			if err != nil {
				err = msgp.WrapError(err, "CollectedAt")
				return
			}
		case "nodes":
			z.Nodes, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Nodes")
				return
			}
		case "transition":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Transition")
					return
				}
				z.Transition = nil
			} else {
				if z.Transition == nil {
					z.Transition = new(ILMQueueStats)
				}
				err = z.Transition.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Transition")
					return
				}
			}
			zb0001Mask |= 0x1
		case "expiry":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Expiry")
					return
				}
				z.Expiry = nil
			} else {
				if z.Expiry == nil {
					z.Expiry = new(ILMQueueStats)
				}
				err = z.Expiry.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Expiry")
					return
				}
			}
			zb0001Mask |= 0x2
		case "restore":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Restore")
					return
				}
				z.Restore = nil
			} else {
				if z.Restore == nil {
					z.Restore = new(ILMRestoreStats)
				}
				err = z.Restore.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Restore")
					return
				}
			}
			zb0001Mask |= 0x4
		case "lastDay":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "LastDay")
					return
				}
				z.LastDay = nil
			} else {
				if z.LastDay == nil {
					z.LastDay = new(SegmentedILMMetrics)
				}
				err = (*Segmented[ILMSegment, *ILMSegment])(z.LastDay).DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "LastDay")
					return
				}
			}
			zb0001Mask |= 0x8
		case "lastHour":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "LastHour")
					return
				}
				z.LastHour = nil
			} else {
				if z.LastHour == nil {
					z.LastHour = new(SegmentedILMMetrics)
				}
				err = (*Segmented[ILMSegment, *ILMSegment])(z.LastHour).DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "LastHour")
					return
				}
			}
			zb0001Mask |= 0x10
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x1f {
		if (zb0001Mask & 0x1) == 0 {
			z.Transition = nil
		}
		if (zb0001Mask & 0x2) == 0 {
			z.Expiry = nil
		}
		if (zb0001Mask & 0x4) == 0 {
			z.Restore = nil
		}
		if (zb0001Mask & 0x8) == 0 {
			z.LastDay = nil
		}
		if (zb0001Mask & 0x10) == 0 {
			z.LastHour = nil
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ILMMetrics) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(7)
	var zb0001Mask uint8 /* 7 bits */
	_ = zb0001Mask
	if z.Transition == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Expiry == nil {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.Restore == nil {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.LastDay == nil {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.LastHour == nil {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "collected"
		err = en.Append(0xa9, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64)
		if err != nil {
			return
		}
		err = en.WriteTime(z.CollectedAt)
		if err != nil {
			err = msgp.WrapError(err, "CollectedAt")
			return
		}
		// write "nodes"
		err = en.Append(0xa5, 0x6e, 0x6f, 0x64, 0x65, 0x73)
		if err != nil {
			return
		}
		err = en.WriteInt(z.Nodes)
		if err != nil {
			err = msgp.WrapError(err, "Nodes")
			return
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "transition"
			err = en.Append(0xaa, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e)
			if err != nil {
				return
			}
			if z.Transition == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = z.Transition.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "Transition")
					return
				}
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "expiry"
			err = en.Append(0xa6, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79)
			if err != nil {
				return
			}
			if z.Expiry == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = z.Expiry.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "Expiry")
					return
				}
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// write "restore"
			err = en.Append(0xa7, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65)
			if err != nil {
				return
			}
			if z.Restore == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = z.Restore.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "Restore")
					return
				}
			}
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// write "lastDay"
			err = en.Append(0xa7, 0x6c, 0x61, 0x73, 0x74, 0x44, 0x61, 0x79)
			if err != nil {
				return
			}
			if z.LastDay == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = (*Segmented[ILMSegment, *ILMSegment])(z.LastDay).EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "LastDay")
					return
				}
			}
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// write "lastHour"
			err = en.Append(0xa8, 0x6c, 0x61, 0x73, 0x74, 0x48, 0x6f, 0x75, 0x72)
			if err != nil {
				return
			}
			if z.LastHour == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = (*Segmented[ILMSegment, *ILMSegment])(z.LastHour).EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "LastHour")
					return
				}
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ILMMetrics) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(7)
	var zb0001Mask uint8 /* 7 bits */
	_ = zb0001Mask
	if z.Transition == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Expiry == nil {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.Restore == nil {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.LastDay == nil {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.LastHour == nil {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "collected"
		o = append(o, 0xa9, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64)
		o = msgp.AppendTime(o, z.CollectedAt)
		// string "nodes"
		o = append(o, 0xa5, 0x6e, 0x6f, 0x64, 0x65, 0x73)
		o = msgp.AppendInt(o, z.Nodes)
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "transition"
			o = append(o, 0xaa, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e)
			if z.Transition == nil {
				o = msgp.AppendNil(o)
			} else {
				o, err = z.Transition.MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "Transition")
					return
				}
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "expiry"
			o = append(o, 0xa6, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79)
			if z.Expiry == nil {
				o = msgp.AppendNil(o)
			} else {
				o, err = z.Expiry.MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "Expiry")
					return
				}
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// string "restore"
			o = append(o, 0xa7, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65)
			if z.Restore == nil {
				o = msgp.AppendNil(o)
			} else {
				o, err = z.Restore.MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "Restore")
					return
				}
			}
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// string "lastDay"
			o = append(o, 0xa7, 0x6c, 0x61, 0x73, 0x74, 0x44, 0x61, 0x79)
			if z.LastDay == nil {
				o = msgp.AppendNil(o)
			} else {
				o, err = (*Segmented[ILMSegment, *ILMSegment])(z.LastDay).MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "LastDay")
					return
				}
			}
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// string "lastHour"
			o = append(o, 0xa8, 0x6c, 0x61, 0x73, 0x74, 0x48, 0x6f, 0x75, 0x72)
			if z.LastHour == nil {
				o = msgp.AppendNil(o)
			} else {
				o, err = (*Segmented[ILMSegment, *ILMSegment])(z.LastHour).MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "LastHour")
					return
				}
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ILMMetrics) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 5 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "collected":
			z.CollectedAt, bts, err = msgp.ReadTimeUTCBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CollectedAt")
				return
			}
		case "nodes":
			z.Nodes, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nodes")
				return
			}
		case "transition":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Transition = nil
			} else {
				if z.Transition == nil {
					z.Transition = new(ILMQueueStats)
				}
				bts, err = z.Transition.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Transition")
					return
				}
			}
			zb0001Mask |= 0x1
		case "expiry":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Expiry = nil
			} else {
				if z.Expiry == nil {
					z.Expiry = new(ILMQueueStats)
				}
				bts, err = z.Expiry.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Expiry")
					return
				}
			}
			zb0001Mask |= 0x2
		case "restore":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Restore = nil
			} else {
				if z.Restore == nil {
					z.Restore = new(ILMRestoreStats)
				}
				bts, err = z.Restore.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Restore")
					return
				}
			}
			zb0001Mask |= 0x4
		case "lastDay":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.LastDay = nil
			} else {
				if z.LastDay == nil {
					z.LastDay = new(SegmentedILMMetrics)
				}
				bts, err = (*Segmented[ILMSegment, *ILMSegment])(z.LastDay).UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "LastDay")
					return
				}
			}
			zb0001Mask |= 0x8
		case "lastHour":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.LastHour = nil
			} else {
				if z.LastHour == nil {
					z.LastHour = new(SegmentedILMMetrics)
				}
				bts, err = (*Segmented[ILMSegment, *ILMSegment])(z.LastHour).UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "LastHour")
					return
				}
			}
			zb0001Mask |= 0x10
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x1f {
		if (zb0001Mask & 0x1) == 0 {
			z.Transition = nil
		}
		if (zb0001Mask & 0x2) == 0 {
			z.Expiry = nil
		}
		if (zb0001Mask & 0x4) == 0 {
			z.Restore = nil
		}
		if (zb0001Mask & 0x8) == 0 {
			z.LastDay = nil
		}
		if (zb0001Mask & 0x10) == 0 {
			z.LastHour = nil
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ILMMetrics) Msgsize() (s int) {
	s = 1 + 10 + msgp.TimeSize + 6 + msgp.IntSize + 11
	if z.Transition == nil {
		s += msgp.NilSize
	} else {
		s += z.Transition.Msgsize()
	}
	s += 7
	if z.Expiry == nil {
		s += msgp.NilSize
	} else {
		s += z.Expiry.Msgsize()
	}
	s += 8
	if z.Restore == nil {
		s += msgp.NilSize
	} else {
		s += z.Restore.Msgsize()
	}
	s += 8
	if z.LastDay == nil {
		s += msgp.NilSize
	} else {
		s += (*Segmented[ILMSegment, *ILMSegment])(z.LastDay).Msgsize()
	}
	s += 9
	if z.LastHour == nil {
		s += msgp.NilSize
	} else {
		s += (*Segmented[ILMSegment, *ILMSegment])(z.LastHour).Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ILMQueueStats) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 8 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "queued":
			z.Queued, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Queued")
				return
			}
			zb0001Mask |= 0x1
		case "capacity":
			z.Capacity, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Capacity")
				return
			}
			zb0001Mask |= 0x2
		case "workers":
			z.Workers, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Workers")
				return
			}
			zb0001Mask |= 0x4
		case "active":
			z.Active, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Active")
				return
			}
			zb0001Mask |= 0x8
		case "missed":
			z.Missed, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Missed")
				return
			}
			zb0001Mask |= 0x10
		case "tasks":
			err = z.Tasks.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Tasks")
				return
			}
			zb0001Mask |= 0x20
		case "errors":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Errors")
				return
			}
			if z.Errors == nil {
				z.Errors = make(map[string]uint64, zb0002)
			} else if len(z.Errors) > 0 {
				clear(z.Errors)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Errors")
					return
				}
				var za0002 uint64
				za0002, err = dc.ReadUint64()
				if err != nil {
					err = msgp.WrapError(err, "Errors", za0001)
					return
				}
				z.Errors[za0001] = za0002
			}
			zb0001Mask |= 0x40
		case "head_queued_at":
			z.HeadQueuedAt, err = dc.ReadTimeUTC()
			if err != nil {
				err = msgp.WrapError(err, "HeadQueuedAt")
				return
			}
			zb0001Mask |= 0x80
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0xff {
		if (zb0001Mask & 0x1) == 0 {
			z.Queued = 0
		}
		if (zb0001Mask & 0x2) == 0 {
			z.Capacity = 0
		}
		if (zb0001Mask & 0x4) == 0 {
			z.Workers = 0
		}
		if (zb0001Mask & 0x8) == 0 {
			z.Active = 0
		}
		if (zb0001Mask & 0x10) == 0 {
			z.Missed = 0
		}
		if (zb0001Mask & 0x20) == 0 {
			z.Tasks = TimedAction{}
		}
		if (zb0001Mask & 0x40) == 0 {
			z.Errors = nil
		}
		if (zb0001Mask & 0x80) == 0 {
			z.HeadQueuedAt = (time.Time{})
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ILMQueueStats) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(8)
	var zb0001Mask uint8 /* 8 bits */
	_ = zb0001Mask
	if z.Queued == 0 {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.Capacity == 0 {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Workers == 0 {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Active == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.Missed == 0 {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.Errors == nil {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.HeadQueuedAt.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// write "queued"
			err = en.Append(0xa6, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.Queued)
			if err != nil {
				err = msgp.WrapError(err, "Queued")
				return
			}
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "capacity"
			err = en.Append(0xa8, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.Capacity)
			if err != nil {
				err = msgp.WrapError(err, "Capacity")
				return
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "workers"
			err = en.Append(0xa7, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.Workers)
			if err != nil {
				err = msgp.WrapError(err, "Workers")
				return
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "active"
			err = en.Append(0xa6, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.Active)
			if err != nil {
				err = msgp.WrapError(err, "Active")
				return
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// write "missed"
			err = en.Append(0xa6, 0x6d, 0x69, 0x73, 0x73, 0x65, 0x64)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.Missed)
			if err != nil {
				err = msgp.WrapError(err, "Missed")
				return
			}
		}
		// write "tasks"
		err = en.Append(0xa5, 0x74, 0x61, 0x73, 0x6b, 0x73)
		if err != nil {
			return
		}
		err = z.Tasks.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Tasks")
			return
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// write "errors"
			err = en.Append(0xa6, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73)
			if err != nil {
				return
			}
			err = en.WriteMapHeader(uint32(len(z.Errors)))
			if err != nil {
				err = msgp.WrapError(err, "Errors")
				return
			}
			for za0001, za0002 := range z.Errors {
				err = en.WriteString(za0001)
				if err != nil {
					err = msgp.WrapError(err, "Errors")
					return
				}
				err = en.WriteUint64(za0002)
				if err != nil {
					err = msgp.WrapError(err, "Errors", za0001)
					return
				}
			}
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// write "head_queued_at"
			err = en.Append(0xae, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x5f, 0x61, 0x74)
			if err != nil {
				return
			}
			err = en.WriteTime(z.HeadQueuedAt)
			if err != nil {
				err = msgp.WrapError(err, "HeadQueuedAt")
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ILMQueueStats) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(8)
	var zb0001Mask uint8 /* 8 bits */
	_ = zb0001Mask
	if z.Queued == 0 {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.Capacity == 0 {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Workers == 0 {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Active == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.Missed == 0 {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.Errors == nil {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.HeadQueuedAt.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// string "queued"
			o = append(o, 0xa6, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64)
			o = msgp.AppendInt64(o, z.Queued)
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "capacity"
			o = append(o, 0xa8, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79)
			o = msgp.AppendInt64(o, z.Capacity)
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "workers"
			o = append(o, 0xa7, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73)
			o = msgp.AppendInt64(o, z.Workers)
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "active"
			o = append(o, 0xa6, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65)
			o = msgp.AppendInt64(o, z.Active)
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// string "missed"
			o = append(o, 0xa6, 0x6d, 0x69, 0x73, 0x73, 0x65, 0x64)
			o = msgp.AppendUint64(o, z.Missed)
		}
		// string "tasks"
		o = append(o, 0xa5, 0x74, 0x61, 0x73, 0x6b, 0x73)
		o, err = z.Tasks.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Tasks")
			return
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// string "errors"
			o = append(o, 0xa6, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73)
			o = msgp.AppendMapHeader(o, uint32(len(z.Errors)))
			for za0001, za0002 := range z.Errors {
				o = msgp.AppendString(o, za0001)
				o = msgp.AppendUint64(o, za0002)
			}
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// string "head_queued_at"
			o = append(o, 0xae, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x5f, 0x61, 0x74)
			o = msgp.AppendTime(o, z.HeadQueuedAt)
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ILMQueueStats) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 8 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "queued":
			z.Queued, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Queued")
				return
			}
			zb0001Mask |= 0x1
		case "capacity":
			z.Capacity, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Capacity")
				return
			}
			zb0001Mask |= 0x2
		case "workers":
			z.Workers, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Workers")
				return
			}
			zb0001Mask |= 0x4
		case "active":
			z.Active, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Active")
				return
			}
			zb0001Mask |= 0x8
		case "missed":
			z.Missed, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Missed")
				return
			}
			zb0001Mask |= 0x10
		case "tasks":
			bts, err = z.Tasks.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Tasks")
				return
			}
			zb0001Mask |= 0x20
		case "errors":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Errors")
				return
			}
			if z.Errors == nil {
				z.Errors = make(map[string]uint64, zb0002)
			} else if len(z.Errors) > 0 {
				clear(z.Errors)
			}
			for zb0002 > 0 {
				var za0002 uint64
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Errors")
					return
				}
				za0002, bts, err = msgp.ReadUint64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Errors", za0001)
					return
				}
				z.Errors[za0001] = za0002
			}
			zb0001Mask |= 0x40
		case "head_queued_at":
			z.HeadQueuedAt, bts, err = msgp.ReadTimeUTCBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "HeadQueuedAt")
				return
			}
			zb0001Mask |= 0x80
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0xff {
		if (zb0001Mask & 0x1) == 0 {
			z.Queued = 0
		}
		if (zb0001Mask & 0x2) == 0 {
			z.Capacity = 0
		}
		if (zb0001Mask & 0x4) == 0 {
			z.Workers = 0
		}
		if (zb0001Mask & 0x8) == 0 {
			z.Active = 0
		}
		if (zb0001Mask & 0x10) == 0 {
			z.Missed = 0
		}
		if (zb0001Mask & 0x20) == 0 {
			z.Tasks = TimedAction{}
		}
		if (zb0001Mask & 0x40) == 0 {
			z.Errors = nil
		}
		if (zb0001Mask & 0x80) == 0 {
			z.HeadQueuedAt = (time.Time{})
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ILMQueueStats) Msgsize() (s int) {
	s = 1 + 7 + msgp.Int64Size + 9 + msgp.Int64Size + 8 + msgp.Int64Size + 7 + msgp.Int64Size + 7 + msgp.Uint64Size + 6 + z.Tasks.Msgsize() + 7 + msgp.MapHeaderSize
	if z.Errors != nil {
		for za0001, za0002 := range z.Errors {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.Uint64Size
		}
	}
	s += 15 + msgp.TimeSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ILMRestoreStats) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "restores":
			err = z.Restores.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Restores")
				return
			}
			zb0001Mask |= 0x1
		case "active":
			z.Active, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Active")
				return
			}
			zb0001Mask |= 0x2
		case "errors":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Errors")
				return
			}
			if z.Errors == nil {
				z.Errors = make(map[string]uint64, zb0002)
			} else if len(z.Errors) > 0 {
				clear(z.Errors)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Errors")
					return
				}
				var za0002 uint64
				za0002, err = dc.ReadUint64()
				if err != nil {
					err = msgp.WrapError(err, "Errors", za0001)
					return
				}
				z.Errors[za0001] = za0002
			}
			zb0001Mask |= 0x4
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x7 {
		if (zb0001Mask & 0x1) == 0 {
			z.Restores = TimedAction{}
		}
		if (zb0001Mask & 0x2) == 0 {
			z.Active = 0
		}
		if (zb0001Mask & 0x4) == 0 {
			z.Errors = nil
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ILMRestoreStats) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(3)
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	if z.Active == 0 {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Errors == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "restores"
		err = en.Append(0xa8, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73)
		if err != nil {
			return
		}
		err = z.Restores.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Restores")
			return
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "active"
			err = en.Append(0xa6, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.Active)
			if err != nil {
				err = msgp.WrapError(err, "Active")
				return
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "errors"
			err = en.Append(0xa6, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73)
			if err != nil {
				return
			}
			err = en.WriteMapHeader(uint32(len(z.Errors)))
			if err != nil {
				err = msgp.WrapError(err, "Errors")
				return
			}
			for za0001, za0002 := range z.Errors {
				err = en.WriteString(za0001)
				if err != nil {
					err = msgp.WrapError(err, "Errors")
					return
				}
				err = en.WriteUint64(za0002)
				if err != nil {
					err = msgp.WrapError(err, "Errors", za0001)
					return
				}
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ILMRestoreStats) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(3)
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	if z.Active == 0 {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Errors == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "restores"
		o = append(o, 0xa8, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73)
		o, err = z.Restores.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Restores")
			return
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "active"
			o = append(o, 0xa6, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65)
			o = msgp.AppendInt64(o, z.Active)
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "errors"
			o = append(o, 0xa6, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73)
			o = msgp.AppendMapHeader(o, uint32(len(z.Errors)))
			for za0001, za0002 := range z.Errors {
				o = msgp.AppendString(o, za0001)
				o = msgp.AppendUint64(o, za0002)
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ILMRestoreStats) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "restores":
			bts, err = z.Restores.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Restores")
				return
			}
			zb0001Mask |= 0x1
		case "active":
			z.Active, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Active")
				return
			}
			zb0001Mask |= 0x2
		case "errors":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Errors")
				return
			}
			if z.Errors == nil {
				z.Errors = make(map[string]uint64, zb0002)
			} else if len(z.Errors) > 0 {
				clear(z.Errors)
			}
			for zb0002 > 0 {
				var za0002 uint64
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Errors")
					return
				}
				za0002, bts, err = msgp.ReadUint64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Errors", za0001)
					return
				}
				z.Errors[za0001] = za0002
			}
			zb0001Mask |= 0x4
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x7 {
		if (zb0001Mask & 0x1) == 0 {
			z.Restores = TimedAction{}
		}
		if (zb0001Mask & 0x2) == 0 {
			z.Active = 0
		}
		if (zb0001Mask & 0x4) == 0 {
			z.Errors = nil
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ILMRestoreStats) Msgsize() (s int) {
	s = 1 + 9 + z.Restores.Msgsize() + 7 + msgp.Int64Size + 7 + msgp.MapHeaderSize
	if z.Errors != nil {
		for za0001, za0002 := range z.Errors {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.Uint64Size
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ILMSegment) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint16 /* 12 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "transition_tasks":
			z.TransitionTasks, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "TransitionTasks")
				return
			}
			zb0001Mask |= 0x1
		case "transition_nanos":
			z.TransitionNanos, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "TransitionNanos")
				return
			}
			zb0001Mask |= 0x2
		case "transition_errors":
			z.TransitionErrors, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "TransitionErrors")
				return
			}
			zb0001Mask |= 0x4
		case "transition_missed":
			z.TransitionMissed, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "TransitionMissed")
				return
			}
			zb0001Mask |= 0x8
		case "expiry_tasks":
			z.ExpiryTasks, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "ExpiryTasks")
				return
			}
			zb0001Mask |= 0x10
		case "expiry_nanos":
			z.ExpiryNanos, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "ExpiryNanos")
				return
			}
			zb0001Mask |= 0x20
		case "expiry_errors":
			z.ExpiryErrors, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "ExpiryErrors")
				return
			}
			zb0001Mask |= 0x40
		case "expiry_missed":
			z.ExpiryMissed, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "ExpiryMissed")
				return
			}
			zb0001Mask |= 0x80
		case "restore_count":
			z.RestoreCount, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "RestoreCount")
				return
			}
			zb0001Mask |= 0x100
		case "restore_bytes":
			z.RestoreBytes, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "RestoreBytes")
				return
			}
			zb0001Mask |= 0x200
		case "restore_nanos":
			z.RestoreNanos, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "RestoreNanos")
				return
			}
			zb0001Mask |= 0x400
		case "restore_errors":
			z.RestoreErrors, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "RestoreErrors")
				return
			}
			zb0001Mask |= 0x800
		case "n":
			z.N, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "N")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0xfff {
		if (zb0001Mask & 0x1) == 0 {
			z.TransitionTasks = 0
		}
		if (zb0001Mask & 0x2) == 0 {
			z.TransitionNanos = 0
		}
		if (zb0001Mask & 0x4) == 0 {
			z.TransitionErrors = 0
		}
		if (zb0001Mask & 0x8) == 0 {
			z.TransitionMissed = 0
		}
		if (zb0001Mask & 0x10) == 0 {
			z.ExpiryTasks = 0
		}
		if (zb0001Mask & 0x20) == 0 {
			z.ExpiryNanos = 0
		}
		if (zb0001Mask & 0x40) == 0 {
			z.ExpiryErrors = 0
		}
		if (zb0001Mask & 0x80) == 0 {
			z.ExpiryMissed = 0
		}
		if (zb0001Mask & 0x100) == 0 {
			z.RestoreCount = 0
		}
		if (zb0001Mask & 0x200) == 0 {
			z.RestoreBytes = 0
		}
		if (zb0001Mask & 0x400) == 0 {
			z.RestoreNanos = 0
		}
		if (zb0001Mask & 0x800) == 0 {
			z.RestoreErrors = 0
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ILMSegment) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(13)
	var zb0001Mask uint16 /* 13 bits */
	_ = zb0001Mask
	if z.TransitionTasks == 0 {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.TransitionNanos == 0 {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.TransitionErrors == 0 {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.TransitionMissed == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.ExpiryTasks == 0 {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.ExpiryNanos == 0 {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.ExpiryErrors == 0 {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.ExpiryMissed == 0 {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.RestoreCount == 0 {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	if z.RestoreBytes == 0 {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	if z.RestoreNanos == 0 {
		zb0001Len--
		zb0001Mask |= 0x400
	}
	if z.RestoreErrors == 0 {
		zb0001Len--
		zb0001Mask |= 0x800
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// write "transition_tasks"
			err = en.Append(0xb0, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x73)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.TransitionTasks)
			if err != nil {
				err = msgp.WrapError(err, "TransitionTasks")
				return
			}
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "transition_nanos"
			err = en.Append(0xb0, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.TransitionNanos)
			if err != nil {
				err = msgp.WrapError(err, "TransitionNanos")
				return
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "transition_errors"
			err = en.Append(0xb1, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.TransitionErrors)
			if err != nil {
				err = msgp.WrapError(err, "TransitionErrors")
				return
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "transition_missed"
			err = en.Append(0xb1, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x69, 0x73, 0x73, 0x65, 0x64)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.TransitionMissed)
			if err != nil {
				err = msgp.WrapError(err, "TransitionMissed")
				return
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// write "expiry_tasks"
			err = en.Append(0xac, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x73)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.ExpiryTasks)
			if err != nil {
				err = msgp.WrapError(err, "ExpiryTasks")
				return
			}
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// write "expiry_nanos"
			err = en.Append(0xac, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.ExpiryNanos)
			if err != nil {
				err = msgp.WrapError(err, "ExpiryNanos")
				return
			}
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// write "expiry_errors"
			err = en.Append(0xad, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.ExpiryErrors)
			if err != nil {
				err = msgp.WrapError(err, "ExpiryErrors")
				return
			}
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// write "expiry_missed"
			err = en.Append(0xad, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x6d, 0x69, 0x73, 0x73, 0x65, 0x64)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.ExpiryMissed)
			if err != nil {
				err = msgp.WrapError(err, "ExpiryMissed")
				return
			}
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// write "restore_count"
			err = en.Append(0xad, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.RestoreCount)
			if err != nil {
				err = msgp.WrapError(err, "RestoreCount")
				return
			}
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// write "restore_bytes"
			err = en.Append(0xad, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.RestoreBytes)
			if err != nil {
				err = msgp.WrapError(err, "RestoreBytes")
				return
			}
		}
		if (zb0001Mask & 0x400) == 0 { // if not omitted
			// write "restore_nanos"
			err = en.Append(0xad, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.RestoreNanos)
			if err != nil {
				err = msgp.WrapError(err, "RestoreNanos")
				return
			}
		}
		if (zb0001Mask & 0x800) == 0 { // if not omitted
			// write "restore_errors"
			err = en.Append(0xae, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.RestoreErrors)
			if err != nil {
				err = msgp.WrapError(err, "RestoreErrors")
				return
			}
		}
		// write "n"
		err = en.Append(0xa1, 0x6e)
		if err != nil {
			return
		}
		err = en.WriteInt(z.N)
		if err != nil {
			err = msgp.WrapError(err, "N")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ILMSegment) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(13)
	var zb0001Mask uint16 /* 13 bits */
	_ = zb0001Mask
	if z.TransitionTasks == 0 {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.TransitionNanos == 0 {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.TransitionErrors == 0 {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.TransitionMissed == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.ExpiryTasks == 0 {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.ExpiryNanos == 0 {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.ExpiryErrors == 0 {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.ExpiryMissed == 0 {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.RestoreCount == 0 {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	if z.RestoreBytes == 0 {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	if z.RestoreNanos == 0 {
		zb0001Len--
		zb0001Mask |= 0x400
	}
	if z.RestoreErrors == 0 {
		zb0001Len--
		zb0001Mask |= 0x800
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// string "transition_tasks"
			o = append(o, 0xb0, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x73)
			o = msgp.AppendUint64(o, z.TransitionTasks)
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "transition_nanos"
			o = append(o, 0xb0, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73)
			o = msgp.AppendUint64(o, z.TransitionNanos)
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "transition_errors"
			o = append(o, 0xb1, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73)
			o = msgp.AppendUint64(o, z.TransitionErrors)
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "transition_missed"
			o = append(o, 0xb1, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x69, 0x73, 0x73, 0x65, 0x64)
			o = msgp.AppendUint64(o, z.TransitionMissed)
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// string "expiry_tasks"
			o = append(o, 0xac, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x73)
			o = msgp.AppendUint64(o, z.ExpiryTasks)
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// string "expiry_nanos"
			o = append(o, 0xac, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73)
			o = msgp.AppendUint64(o, z.ExpiryNanos)
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// string "expiry_errors"
			o = append(o, 0xad, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73)
			o = msgp.AppendUint64(o, z.ExpiryErrors)
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// string "expiry_missed"
			o = append(o, 0xad, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x6d, 0x69, 0x73, 0x73, 0x65, 0x64)
			o = msgp.AppendUint64(o, z.ExpiryMissed)
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// string "restore_count"
			o = append(o, 0xad, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74)
			o = msgp.AppendUint64(o, z.RestoreCount)
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// string "restore_bytes"
			o = append(o, 0xad, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73)
			o = msgp.AppendUint64(o, z.RestoreBytes)
		}
		if (zb0001Mask & 0x400) == 0 { // if not omitted
			// string "restore_nanos"
			o = append(o, 0xad, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73)
			o = msgp.AppendUint64(o, z.RestoreNanos)
		}
		if (zb0001Mask & 0x800) == 0 { // if not omitted
			// string "restore_errors"
			o = append(o, 0xae, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73)
			o = msgp.AppendUint64(o, z.RestoreErrors)
		}
		// string "n"
		o = append(o, 0xa1, 0x6e)
		o = msgp.AppendInt(o, z.N)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ILMSegment) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint16 /* 12 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "transition_tasks":
			z.TransitionTasks, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TransitionTasks")
				return
			}
			zb0001Mask |= 0x1
		case "transition_nanos":
			z.TransitionNanos, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TransitionNanos")
				return
			}
			zb0001Mask |= 0x2
		case "transition_errors":
			z.TransitionErrors, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TransitionErrors")
				return
			}
			zb0001Mask |= 0x4
		case "transition_missed":
			z.TransitionMissed, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TransitionMissed")
				return
			}
			zb0001Mask |= 0x8
		case "expiry_tasks":
			z.ExpiryTasks, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ExpiryTasks")
				return
			}
			zb0001Mask |= 0x10
		case "expiry_nanos":
			z.ExpiryNanos, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ExpiryNanos")
				return
			}
			zb0001Mask |= 0x20
		case "expiry_errors":
			z.ExpiryErrors, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ExpiryErrors")
				return
			}
			zb0001Mask |= 0x40
		case "expiry_missed":
			z.ExpiryMissed, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ExpiryMissed")
				return
			}
			zb0001Mask |= 0x80
		case "restore_count":
			z.RestoreCount, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RestoreCount")
				return
			}
			zb0001Mask |= 0x100
		case "restore_bytes":
			z.RestoreBytes, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RestoreBytes")
				return
			}
			zb0001Mask |= 0x200
		case "restore_nanos":
			z.RestoreNanos, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RestoreNanos")
				return
			}
			zb0001Mask |= 0x400
		case "restore_errors":
			z.RestoreErrors, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RestoreErrors")
				return
			}
			zb0001Mask |= 0x800
		case "n":
			z.N, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "N")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0xfff {
		if (zb0001Mask & 0x1) == 0 {
			z.TransitionTasks = 0
		}
		if (zb0001Mask & 0x2) == 0 {
			z.TransitionNanos = 0
		}
		if (zb0001Mask & 0x4) == 0 {
			z.TransitionErrors = 0
		}
		if (zb0001Mask & 0x8) == 0 {
			z.TransitionMissed = 0
		}
		if (zb0001Mask & 0x10) == 0 {
			z.ExpiryTasks = 0
		}
		if (zb0001Mask & 0x20) == 0 {
			z.ExpiryNanos = 0
		}
		if (zb0001Mask & 0x40) == 0 {
			z.ExpiryErrors = 0
		}
		if (zb0001Mask & 0x80) == 0 {
			z.ExpiryMissed = 0
		}
		if (zb0001Mask & 0x100) == 0 {
			z.RestoreCount = 0
		}
		if (zb0001Mask & 0x200) == 0 {
			z.RestoreBytes = 0
		}
		if (zb0001Mask & 0x400) == 0 {
			z.RestoreNanos = 0
		}
		if (zb0001Mask & 0x800) == 0 {
			z.RestoreErrors = 0
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ILMSegment) Msgsize() (s int) {
	s = 1 + 17 + msgp.Uint64Size + 17 + msgp.Uint64Size + 18 + msgp.Uint64Size + 18 + msgp.Uint64Size + 13 + msgp.Uint64Size + 13 + msgp.Uint64Size + 14 + msgp.Uint64Size + 14 + msgp.Uint64Size + 14 + msgp.Uint64Size + 14 + msgp.Uint64Size + 14 + msgp.Uint64Size + 15 + msgp.Uint64Size + 2 + msgp.IntSize
	return
}
